=== google/devlibrary/shared/schema/AuthorMetadata.json
{
  "$id": "https://example.com/address.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "AuthorMetadata",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The author's name"
    },
    "bio": {
      "type": "string",
      "description": "Short author bio"
    },
    "photoURL": {
      "type": "string",
      "description": "Public URL to their profile photo"
    },
    "interviewVideoId": {
      "type": "string",
      "description": "YouTube video id for their video interview"
    },
    "githubURL": {
      "type": "string",
      "description": "Public URL to their GitHub profile"
    },
    "mediumURL": {
      "type": "string",
      "description": "Public URL to their Medium profile"
    }
  },
  "required": [ "name", "bio", "photoURL" ]
}

=== google/devlibrary/config/authors/hamidfathi1998.json
{
  "name": "Hamid Fathi,",
  "bio": "Android Developer with high experience and a demonstrated history of working in the computer software industry and Iran's and Netherland's biggest tech comp",
  "photoURL": "https://avatars.githubusercontent.com/hamidfathi1998",
  "githubURL": "https://github.com/hamidfathi1998"
}

=== google/devlibrary/config/authors/aravindvnair99.json
{
  "name": "Aravind V. Nair",
  "bio": "Google DSC Lead for ASEB, Full-stack Web Developer, Cloud Computing and Cybersecurity Enthusiast, ex-Google TC member, Kung Fu black belt",
  "photoURL": "https://avatars.githubusercontent.com/AravindVNair99",
  "githubURL": "https://github.com/AravindVNair99"
}

=== google/devlibrary/config/authors/shubham.json
{
  "name": "Shubham Datta",
  "bio": "Coprorate Develpment @goClio (ex-@Shopify) + Host @BackbonePodcast | write about #tech, #investing, #finance, #SaaS | more: www.shubhamdatta.com",
  "photoURL": "https://miro.medium.com/v2/resize:fit:2400/1*CooH29d_7r3I78e9Z1pvlA.jpeg",
  "mediumURL": "https://medium.com/@shubham"
}

=== google/devlibrary/config/authors/vmadalin.json
{
  "name": "Madalin Valceleanu",
  "bio": "Mobile Software Developer @Vonage\r\n\r\nEnthusiast and passionate about clean code, modular architecture, design patterns and automation.\r\nğŸ‡·ğŸ‡´ - ğŸ‡ªğŸ‡¸ - ğŸ‡¬ğŸ‡§",
  "photoURL": "https://avatars.githubusercontent.com/VMadalin",
  "githubURL": "https://github.com/VMadalin"
}

=== google/devlibrary/config/authors/arthurstarks.json
{
  "name": "Arthur KAZA",
  "bio": "Senior Machine Learning Engineer | Google Developer Group Kinshasa Co-Organizer | AI Product Strategy Lead Engineer | Business Intelligence | AI Architect",
  "photoURL": "https://avatars.githubusercontent.com/ArthurStarks",
  "githubURL": "https://github.com/ArthurStarks"
}
