=== google/devlibrary/shared/schema/BlogMetadata.json
{
  "$id": "https://example.com/address.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "BlogMetadata",
  "type": "object",
  "properties": {
    "version": {
      "type": "number",
      "description": "Internal schema version"
    },
    "source": {
      "type": "string",
      "description": "'medium' or 'other'"
    },
    "authorIds": {
      "type": "array",
      "description": "The Dev Library ID of the author(s)",
      "items": {
        "type": "string",
        "pattern": "^[a-z0-9\\-_]+$"
      }
    },
    "author": {
      "type": "string",
      "description": "The name of the human author"
    },
    "title": {
      "type": "string",
      "description": "The title of the blog post"
    },
    "link": {
      "type": "string",
      "description": "Full external link to the post"
    },
    "tags": {
      "type": "array",
      "minItems": 1,
      "description": "Array of product-specific string tags",
      "items": {
        "type": "string",
        "pattern": "^[a-z-]+$"
      }
    },
    "expertise": {
      "type": "string",
      "description": "The expertise of the articles or projects"
    }
  },
  "required": [ "author", "title", "link", "tags", "expertise", "authorIds"]
}

=== google/devlibrary/config/flutter/blogs/30-flutter-tips-ft-2-3a232899910.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "medium",
  "authorIds": ["lakshydeep-14"],
  "author": "Lakshydeep Vikram Sah",
  "title": "Messaging With Firebase In Flutter",
  "link": "https://lakshydeep-14.medium.com/30-flutter-tips-ft-2-3a232899910",
  "tags": [
    "mobile",
    "firebase",
    "samples"
  ]
}

=== google/devlibrary/config/cloud/blogs/posts-gke-workload-identity.json
{
  "expertise": "BEGINNER",
  "version": 1,
  "source": "other",
  "authorIds": ["pradeepbhadani"],
  "author": "Pradeep Bhadani",
  "title": "Enabling GKE Workload Identity",
  "link": "https://pbhadani.com/posts/gke-workload-identity/",
  "tags": [
    "containers",
    "developer-tools",
    "security-identity"
  ]
}

=== google/devlibrary/config/flutter/blogs/open-source-projects-in-flutter-b6fa96f4d8fc.json
{
  "expertise": "BEGINNER",
  "version": 1,
  "source": "medium",
  "authorIds": [
    "adityathakurxd"
  ],
  "author": "Aditya Thakur",
  "title": "Open Source projects in Flutter",
  "link": "https://adityathakurxd.medium.com/open-source-projects-in-flutter-b6fa96f4d8fc",
  "tags": [
    "mobile",
    "plugins",
    "samples"
  ]
}

=== google/devlibrary/config/flutter/blogs/uploading-flutter-projects-on-firebase-hosting-5d41d469b778.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "medium",
  "authorIds": [
    "ayeshaiftikhar"
  ],
  "author": "Ayesha Iftikhar",
  "title": "Uploading Flutter Projects on Firebase Hosting",
  "link": "https://medium.com/flutterevo/uploading-flutter-projects-on-firebase-hosting-5d41d469b778",
  "tags": [
    "firebase",
    "web",
    "general"
  ]
}

=== google/devlibrary/config/flutter/blogs/flutter-ci-cd-web-host-in-firebase-using-github-action.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "other",
  "authorIds": [
    "robertrobinson"
  ],
  "author": "Robert Robinson R",
  "title": "Flutter CI/CD Web host in Firebase using GitHub Action - Robert's Blog",
  "link": "https://robertrobinson.in/flutter-ci-cd-web-host-in-firebase-using-github-action/",
  "tags": [
    "mobile"
  ]
}

=== google/devlibrary/config/flutter/blogs/infiniteoverflow-create-an-api-with-dart-heroku-477k.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "other",
  "authorIds": [
    "infiniteoverflow"
  ],
  "author": "Aswin Gopinathan",
  "title": "Create an API with Dart + Heroku",
  "link": "https://dev.to/infiniteoverflow/create-an-api-with-dart-heroku-477k",
  "tags": [
    "mobile",
    "plugins"
  ]
}

=== google/devlibrary/config/flutter/blogs/building-a-complete-tic-tac-toe-app-in-flutter-a136ea8db390.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "medium",
  "authorIds": [
    "champ96k"
  ],
  "author": "Tushar Ramesh Nikam",
  "title": "Building Complete Tic-Tac-Toe app in Flutter with Splash Screen",
  "link": "https://champ96k.medium.com/building-a-complete-tic-tac-toe-app-in-flutter-a136ea8db390",
  "tags": [
    "mobile"
  ]
}

=== google/devlibrary/config/android/blogs/24508555-android-drag-and-drop-tutorial-moving-views-and-data.json
{
  "expertise": "BEGINNER",
  "version": 1,
  "source": "other",
  "authorIds": [
    "kkumar"
  ],
  "author": "Kushal Kumar R",
  "title": "Android Drag and Drop Tutorial: Moving Views and Data",
  "link": "https://www.raywenderlich.com/24508555-android-drag-and-drop-tutorial-moving-views-and-data",
  "tags": [
    "ui"
  ]
}
