=== google/devlibrary/shared/schema/BlogMetadata.json
{
  "$id": "https://example.com/address.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "BlogMetadata",
  "type": "object",
  "properties": {
    "version": {
      "type": "number",
      "description": "Internal schema version"
    },
    "source": {
      "type": "string",
      "description": "'medium' or 'other'"
    },
    "authorIds": {
      "type": "array",
      "description": "The Dev Library ID of the author(s)",
      "items": {
        "type": "string",
        "pattern": "^[a-z0-9\\-_]+$"
      }
    },
    "author": {
      "type": "string",
      "description": "The name of the human author"
    },
    "title": {
      "type": "string",
      "description": "The title of the blog post"
    },
    "link": {
      "type": "string",
      "description": "Full external link to the post"
    },
    "tags": {
      "type": "array",
      "minItems": 1,
      "description": "Array of product-specific string tags",
      "items": {
        "type": "string",
        "pattern": "^[a-z-]+$"
      }
    },
    "expertise": {
      "type": "string",
      "description": "The expertise of the articles or projects"
    }
  },
  "required": [ "author", "title", "link", "tags", "expertise", "authorIds"]
}

=== google/devlibrary/config/cloud/blogs/cloud-data-fusion-update-deployed-pipelines-through-rest-api-2be0ad25e25f.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "medium",
  "authorIds": [
    "jtaras"
  ],
  "author": "Justin Taras",
  "title": "Cloud Data Fusion: Update deployed pipelines through REST API",
  "link": "https://jtaras.medium.com/cloud-data-fusion-update-deployed-pipelines-through-rest-api-2be0ad25e25f",
  "tags": [
    "data-analytics"
  ]
}

=== google/devlibrary/config/android/blogs/2022-06-concat-adapter.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "other",
  "authorIds": [
    "wajahatkarim"
  ],
  "author": "Wajahat Karim",
  "title": "Beginner's Guide on ConcatAdapter in Android",
  "link": "https://wajahatkarim.com/2022/06/concat-adapter/",
  "tags": [
    "modern-android-development"
  ]
}

=== google/devlibrary/config/flutter/blogs/add-location-sharing-to-a-messaging-app-using-flutter-2386bb18ef62.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "medium",
  "authorIds": [
    "nash0x7e2"
  ],
  "author": "Neevash Ramdial",
  "title": "Add location sharing to a messaging app using Flutter.",
  "link": "https://medium.com/@Nash0x7E2/add-location-sharing-to-a-messaging-app-using-flutter-2386bb18ef62",
  "tags": [
    "mobile",
    "general"
  ]
}

=== google/devlibrary/config/flutter/blogs/vinaytiparadi-implementing-android-12-material-yous-monet-theme-engine-in-flutter-20a8.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "other",
  "authorIds": [
    "vinaytiparadi"
  ],
  "author": "Vinay Tiparadi",
  "title": "Implementing Android 12 Material You's Monet theme engine in Flutter",
  "link": "https://dev.to/vinaytiparadi/implementing-android-12-material-yous-monet-theme-engine-in-flutter-20a8",
  "tags": [
    "mobile",
    "widgets",
    "general"
  ]
}

=== google/devlibrary/config/flutter/blogs/integrating-firebase-to-your-flutter-app-using-flutterfire-cli.json
{
  "expertise": "BEGINNER",
  "version": 1,
  "source": "other",
  "authorIds": ["idrisadeyemi01"],
  "author": "Idris Idris",
  "title": "How to integrate Firebase in a Flutter app using FlutterFire CLI",
  "link": "https://idrisadeyemi.hashnode.dev/integrating-firebase-to-your-flutter-app-using-flutterfire-cli",
  "tags": [
    "firebase",
    "mobile",
    "general"
  ]
}

=== google/devlibrary/config/firebase/blogs/the-comprehensive-guide-to-github-actions-and-firebase-hosting.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "medium",
  "authorIds": [
    "davideast"
  ],
  "author": "David East",
  "title": "The comprehensive guide to GitHub Actions and Firebase Hosting",
  "link": "https://medium.com/firebase-developers/the-comprehensive-guide-to-github-actions-and-firebase-hosting-818502d86c31",
  "tags": [
    "web"
  ]
}

=== google/devlibrary/config/cloud/blogs/bigquery-omni-with-aws-ca2042eccda6.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "medium",
  "authorIds": [
    "chillcaley"
  ],
  "author": "Jaeyeon Baek",
  "title": "BigQuery Omni with AWS",
  "link": "https://medium.com/@chillcaley/bigquery-omni-with-aws-ca2042eccda6",
  "tags": ["ai-ml",
  "api-management",
  "compute",
  "containers",
  "data-analytics",
  "databases",
  "developer-tools",
  "healthcare-life-sciences",
  "hybrid-multicloud",
  "iot",
  "management-tools",
  "media-gaming",
  "migration",
  "networking",
  "operations",
  "security-identity",
  "serverless-computing",
  "storage"]
}

=== google/devlibrary/config/android/blogs/regional-preferences-android14-c3e90a01e65f.json
{
  "expertise": "BEGINNER",
  "version": 1,
  "source": "medium",
  "authorIds": [
    "navczydev"
  ],
  "author": "Nav Singh",
  "title": "Regional Preferences-Android14",
  "link": "https://navczydev.medium.com/regional-preferences-android14-c3e90a01e65f",
  "tags": [
    "modern-android-development",
    "compose"
  ]
}
