=== google/devlibrary/shared/schema/BlogMetadata.json
{
  "$id": "https://example.com/address.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "BlogMetadata",
  "type": "object",
  "properties": {
    "version": {
      "type": "number",
      "description": "Internal schema version"
    },
    "source": {
      "type": "string",
      "description": "'medium' or 'other'"
    },
    "authorIds": {
      "type": "array",
      "description": "The Dev Library ID of the author(s)",
      "items": {
        "type": "string",
        "pattern": "^[a-z0-9\\-_]+$"
      }
    },
    "author": {
      "type": "string",
      "description": "The name of the human author"
    },
    "title": {
      "type": "string",
      "description": "The title of the blog post"
    },
    "link": {
      "type": "string",
      "description": "Full external link to the post"
    },
    "tags": {
      "type": "array",
      "minItems": 1,
      "description": "Array of product-specific string tags",
      "items": {
        "type": "string",
        "pattern": "^[a-z-]+$"
      }
    },
    "expertise": {
      "type": "string",
      "description": "The expertise of the articles or projects"
    }
  },
  "required": [ "author", "title", "link", "tags", "expertise", "authorIds"]
}

=== google/devlibrary/config/android/blogs/geofencing-for-boost-your-digital-campaign-b890afe14dee.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "medium",
  "authorIds": [
    "veroanggra"
  ],
  "author": "Veronica Putri Anggraini",
  "title": "Geofencing for boost your digital campaign",
  "link": "https://veroanggra.medium.com/geofencing-for-boost-your-digital-campaign-b890afe14dee",
  "tags": [
    "kotlin",
    "modern-android-development"
  ]
}

=== google/devlibrary/config/flutter/blogs/using-tensorflow-lite-with-flutter-apps.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "other",
  "authorIds": [
    "amishakirti6410"
  ],
  "author": "Amisha Kirti",
  "title": "Using Tensorflow Lite with Flutter Apps",
  "link": "https://amishakirti6410.hashnode.dev/using-tensorflow-lite-with-flutter-apps",
  "tags": [
    "mobile"
  ]
}

=== google/devlibrary/config/cloud/blogs/transfer-youtube-statistics-data-to-google-sheets-using-google-apps-script-f8adab2103ed.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "medium",
  "authorIds": [
    "aryanirani123"
  ],
  "author": "Aryan Irani",
  "title": "Transfer YouTube Statistics to Google Sheets using the YouTube Data API and Google Apps Script",
  "link": "https://aryanirani123.medium.com/transfer-youtube-statistics-data-to-google-sheets-using-google-apps-script-f8adab2103ed",
  "tags": [
    "developer-tools",
    "api-management"
  ]
}

=== google/devlibrary/config/cloud/blogs/monitoring-iot-data-grafana.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "other",
  "authorIds": [
    "leozz37"
  ],
  "author": "Leonardo Lima",
  "title": "Monitoring data from IoT devices with Go and Grafana",
  "link": "https://cloud.google.com/community/tutorials/monitoring-iot-data-grafana",
  "tags": [
    "iot",
    "operations"
  ]
}

=== google/devlibrary/config/ml/blogs/gateremark-python-from-the-word-go-pt2-31k0.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "other",
  "authorIds": [
    "gateremark"
  ],
  "author": "Mark Gatere",
  "title": "Python from the word ...Go (Pt2)",
  "link": "https://dev.to/gateremark/python-from-the-word-go-pt2-31k0",
  "tags": [
    "mobile",
    "nlp",
    "vision",
    "library",
    "notebook",
    "collection",
    "web",
    "theory"
  ]
}

=== google/devlibrary/config/ml/blogs/notebooks-flax-vision-diffusion-2022-12-16-Stable_Diffusion_in_Flax_Deep_Dive_Part_I.json
{
  "expertise": "ADVANCED",
  "version": 1,
  "source": "other",
  "authorIds": ["bachiirc"],
  "author": "Bachir Chihani",
  "title": "Deep Dive into Stable Diffusion - Part I",
  "link": "https://dzlab.github.io/notebooks/flax/vision/diffusion/2022/12/16/Stable_Diffusion_in_Flax_Deep_Dive_Part_I.html",
  "tags": [
    "vision",
    "gan"
  ]
}

=== google/devlibrary/config/flutter/blogs/flutter-establishing-coding-standards-in-your-team-fe2f0a2808a2.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "medium",
  "authorIds": [
    "crizantlai"
  ],
  "author": "Crizant Lai",
  "title": "Flutter: Establishing coding standards in your team",
  "link": "https://medium.com/nerd-for-tech/flutter-establishing-coding-standards-in-your-team-fe2f0a2808a2",
  "tags": [
    "mobile"
  ]
}

=== google/devlibrary/config/angular/blogs/ngrx-using-ngrx-packages-with-standalone-angular-features-53d8.json
{
  "expertise": "INTERMEDIATE",
  "version": 1,
  "source": "other",
  "authorIds": [
    "markostanimirovic"
  ],
  "author": "Marko StanimiroviÄ‡",
  "title": "Using NgRx Packages with Standalone Angular Features",
  "link": "https://dev.to/ngrx/using-ngrx-packages-with-standalone-angular-features-53d8",
  "tags": [
    "demos"
  ]
}
